//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadonnhap()
        {
            this.chitiethoadonnhaps = new HashSet<chitiethoadonnhap>();
        }
    
        public int mahdn { get; set; }
        public Nullable<int> manv { get; set; }
        public Nullable<int> mancc { get; set; }
        public Nullable<double> tongtien { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadonnhap> chitiethoadonnhaps { get; set; }
        public virtual nhacungcap nhacungcap { get; set; }
    }
}
