//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitiethoadonbans = new HashSet<chitiethoadonban>();
            this.chitiethoadonnhaps = new HashSet<chitiethoadonnhap>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public Nullable<int> maloaisp { get; set; }
        public Nullable<double> giaban { get; set; }
        public string size { get; set; }
        public string dacdiem { get; set; }
        public string anh { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string chitietsp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadonban> chitiethoadonbans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadonnhap> chitiethoadonnhaps { get; set; }
        public virtual loaisp loaisp { get; set; }
    }
}
